spring.application.name=GestorTorneos
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.qgialfjearsmlyqpgofd
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=local

logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG

server.port=8080

openai.api.key=${OPENAI_API_KEY}
openai.embedding.model=text-embedding-3-small

supabase.url=https://qgialfjearsmlyqpgofd.supabase.co
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.storage.bucket=pdfs
